#!/bin/bash

PACKAGE="${PACKAGE} qtcreator yad nginx code gnome-builder ruby go composer php nodejs-lts-jod docker "
AURPACK="${AURPACK} "
FLATPAK=(  )
RDAEMON="${RDAEMON} nginx "
GDAEMON="${GDAEMON}"


## CONFIGS
if [[ -d "$appdir/distros/config" ]]; then
    cp -fr "$appdir/distros/config/"* "$appdir/config/define/"
fi